SPID_ATTRIBUTES = [
    "spidCode",
    "name",
    "familyName",
    "placeOfBirth",
    "countyOfBirth",
    "dateOfBirth",
    "gender",
    "companyName",
    "registeredOffice",
    "fiscalNumber",
    "ivaCode",
    "idCard",
    "mobilePhone",
    "email",
    "address",
    "digitalAddress",
    "expirationDate",
    # Avviso SPID n27 e nr15
    "companyFiscalNumber",
    # Avviso SPID n25: 'address' replaced by these attributes
    "domicileStreetAddress",
    "domicilePostalCode",
    "domicileMunicipality",
    "domicileProvince",
    "domicileNation",
]
