MAP = {
    #"identifier": "urn:oasis:names:tc:SAML:2.0:attrname-format:basic",
    # it should be basic but pySAML2 if this is not specified in SAML response it will handle as uri
    "identifier":  'urn:oasis:names:tc:SAML:2.0:attrname-format:basic',
    "fro": {
        "spidCode":"spidCode",
        "name":"name",
        "familyName":"familyName",
        "placeOfBirth":"placeOfBirth",
        "countyOfBirth":"countyOfBirth",
        "dateOfBirth":"dateOfBirth",
        "gender":"gender",
        "companyName":"companyName",
        "registeredOffice":"registeredOffice",
        "fiscalNumber":"fiscalNumber",
        "ivaCode":"ivaCode",
        "idCard":"idCard",
        "mobilePhone":"mobilePhone",
        "email":"email",
        "address":"address",
        "expirationDate":"expirationDate",
        "digitalAddress":"digitalAddress",
        },
    "to": {
        "spidCode":"spidCode",
        "name":"name",
        "familyName":"familyName",
        "placeOfBirth":"placeOfBirth",
        "countyOfBirth":"countyOfBirth",
        "dateOfBirth":"dateOfBirth",
        "gender":"gender",
        "companyName":"companyName",
        "registeredOffice":"registeredOffice",
        "fiscalNumber":"fiscalNumber",
        "ivaCode":"ivaCode",
        "idCard":"idCard",
        "mobilePhone":"mobilePhone",
        "email":"email",
        "address":"address",
        "expirationDate":"expirationDate",
        "digitalAddress":"digitalAddress",
    }
}
